100: Position now uses dynamic leverage
handle-fi/handle-sdk pull request #105
Opened 2022-05-17 00:52 UTC by Preston-Harrison

resolves #100

2022-05-17 02:29 UTC, rellfy requested changes
~~We should move the files from `src/components/Trade/position/` to `src/utils/trade/position`~~ Ignore, I thought this was the react app

2022-05-17 02:49 UTC, rellfy requested changes
Some comments

2022-05-17 02:49 UTC, rellfy commented on src/components/Trade/position/getLeverage.ts
> +export function getLeverage({
If the `this` context is not used, this should be an arrow function

2022-05-17 02:49 UTC, rellfy commented on src/components/Trade/position/getLeverage.ts
> +  let nextSize = increaseSize ? size.add(sizeDelta) : size.sub(sizeDelta);
```suggestion
  const nextSize = increaseSize ? size.add(sizeDelta) : size.sub(sizeDelta);
```

2022-05-17 02:49 UTC, rellfy commented on src/components/Trade/position/getLeverage.ts
> +};
```suggestion
type GetLeverageArgs = PositionDelta & {
  size: BigNumber;
  collateral: BigNumber;
  entryFundingRate?: BigNumber;
  cumulativeFundingRate?: BigNumber;
  hasProfit: boolean;
  delta?: BigNumber;
};
```

2022-05-17 02:49 UTC, rellfy commented on src/components/Trade/position/getLeverage.ts
> +};
This makes `increaseSize` required, which makes sense because it is an important argument that should not be implied to be "decrease position" when omitted

2022-05-17 05:24 UTC, Preston-Harrison commented on src/components/Trade/position/getLeverage.ts
> +};
moved to a different argument

2022-05-17 05:25 UTC, Preston-Harrison commented on src/components/Trade/position/getLeverage.ts
> +  let nextSize = increaseSize ? size.add(sizeDelta) : size.sub(sizeDelta);
done

2022-05-17 05:25 UTC, Preston-Harrison commented on src/components/Trade/position/getLeverage.ts
> +export function getLeverage({
done

2022-05-20 00:39 UTC, nabsta-eth approved these changes

2022-05-23 06:03 UTC, rellfy approved these changes

2022-05-23 06:04 UTC, merged