84: Follow tokenlists.org standard
handle-fi/handle-sdk pull request #106
Opened 2022-05-18 06:17 UTC by Preston-Harrison

resolves #84

2022-05-19 07:11 UTC, nabsta-eth submitted a review, later dismissed

2022-05-20 00:47 UTC, rellfy requested changes

2022-05-20 00:47 UTC, rellfy commented on src/components/Collaterals.ts
> +  public getIndexedCollaterals = async (): Promise<Omit<Collateral, "name" | "chainId">[]> => {
Don't omit these

2022-05-20 00:47 UTC, rellfy commented on src/components/Collaterals.ts
> +  ): Omit<Collateral, "chainId" | "name"> => {
Don't omit these

2022-05-20 00:47 UTC, rellfy commented on src/components/Convert/Convert.ts
> +  network: Network;
Why have this? Network can be fetched from provider. It doesn't seem like it's used?

2022-05-20 00:47 UTC, rellfy commented on src/components/Convert/Convert.ts
> +  tokenList: TokenInfo[];
Remove this and use an internal SDK token list as it is only used for fetching fees, shouldn't be a public input

2022-05-20 00:47 UTC, rellfy commented on src/components/Convert/Convert.ts
> +  };
Should also add `providerOrSigner?` as a parameter, and if defined we need to check that it matches the returned network.

2022-05-20 00:47 UTC, rellfy commented on src/components/Convert/Convert.ts
> +  tokenList: TokenInfo[];
Remove this

2022-05-20 00:47 UTC, rellfy commented on src/components/Convert/getApiFeeAsPercentage.ts
> +  tokenList: TokenInfo[]
Remove this, import an internal list

2022-05-20 00:47 UTC, rellfy commented on src/components/FxTokens.ts
> +// import { getTokensFromAddresses } from "../utils/fxToken-utils";
If not used please remove

2022-05-20 03:55 UTC, Preston-Harrison commented on src/components/Convert/getApiFeeAsPercentage.ts
> +  tokenList: TokenInfo[]
added a static list in convert

2022-05-20 03:55 UTC, Preston-Harrison commented on src/components/FxTokens.ts
> +// import { getTokensFromAddresses } from "../utils/fxToken-utils";
done

2022-05-22 23:46 UTC, Preston-Harrison commented on src/components/Convert/Convert.ts
> +  };
done

2022-05-22 23:47 UTC, Preston-Harrison commented on src/components/Convert/Convert.ts
> +  tokenList: TokenInfo[];
done

2022-05-23 00:37 UTC, rellfy requested changes

2022-05-23 00:37 UTC, rellfy commented on src/components/FxTokens.ts
> +type Price = {
```suggestion
type FxTokenMulticall = {
```
It is used in a multicall and might return more than just the price in the future

2022-05-23 00:37 UTC, rellfy commented on src/components/TokenManager/handle-tokens.json
> +  "timestamp": "2022-05-18T01:09:39+0000",
We want this file in the handle-react repo, so we can load it by a `handle.fi` URL. It's easier to update & distribute it that way. Otherwise we need to release a new SDK version and also update in handle-react. Since the SDK relies on internet connection to do anything useful, it isn't a problem to have it in handle-react.

2022-05-23 00:40 UTC, Preston-Harrison commented on src/components/Bridge.ts
> +    const account = args.address ?? (await signer.getAddress());
The linter did it

2022-05-23 02:45 UTC, rellfy requested changes

2022-05-23 02:45 UTC, rellfy commented on src/config/hlp.ts
> +// import config from ".";
Please remove if not using

2022-05-23 02:45 UTC, rellfy commented on src/types/fxTokens.ts
> +export type FxTokenPriced = FxToken & {
Please remove and use `FxToken` with the `price` property

2022-05-23 02:45 UTC, rellfy commented on src/utils/tokenlist-utils.ts
> +}
```suggestion
```

2022-05-23 02:45 UTC, rellfy commented on tests/suites/vault-utils/calculateCollateralAsEth.test.ts
> +    // TODO figure out why this test randomly fails
We might want to skip this test with `xit` if it's not solved yet, and create an issue for it, just so publishing doesn't fail.

2022-05-24 01:10 UTC, Preston-Harrison commented on src/components/FxTokens.ts
> +type Price = {
this type is actually not used anywhere, so I have removed it. The type FxToken now includes a price.

2022-05-24 01:14 UTC, Preston-Harrison commented on src/components/FxTokens.ts
> +type Price = {
changed to FxTokenMulticallResponse

2022-05-24 02:35 UTC, Preston-Harrison commented on src/config/hlp.ts
> +// import config from ".";
done

2022-05-24 05:46 UTC, rellfy approved these changes

2022-05-24 22:58 UTC, nabsta-eth approved these changes

2022-05-24 23:10 UTC, merged