111 - Remove duplicates from token list
handle-fi/handle-sdk pull request #112
Opened 2022-05-25 06:55 UTC by Preston-Harrison

resolves #111

2022-05-26 01:28 UTC, rellfy commented
Tests are failing

2022-05-26 01:29 UTC, rellfy requested changes

2022-05-26 01:29 UTC, rellfy commented on src/components/TokenManager/index.ts
> +    }
This should be a private function.

2022-05-26 01:29 UTC, rellfy commented on src/components/TokenManager/index.ts
> +  public getLoadedTokens(network?: Network | number, removeDuplicates = false): TokenInfo[] {
It should default to true, I can't see an use case where you want duplicates.

2022-05-26 23:29 UTC, Preston-Harrison commented on src/components/TokenManager/index.ts
> +  public getLoadedTokens(network?: Network | number, removeDuplicates = false): TokenInfo[] {
Removing duplicates can involve alot of iterations over the entire token list, and for most cases when you are just getting a token by a symbol or address, duplicates are fine. Duplicates only need to be removed when the entire token list is needed at once

2022-05-26 23:45 UTC, Preston-Harrison commented on src/components/TokenManager/index.ts
> +    }
extracted to a public function as it is conceivable removing duplicate tokens might be needed outside of internal functions

2022-05-26 23:58 UTC, rellfy approved these changes

2022-05-27 00:29 UTC, nabsta-eth approved these changes

2022-05-27 00:53 UTC, merged