HP-341
handle-fi/handle-sdk pull request #15
Opened 2021-08-03 10:34 UTC by ahinchliff

https://dltx.atlassian.net/browse/HP-341

2021-08-03 22:01 UTC, rellfy requested changes

2021-08-03 22:01 UTC, rellfy commented on src/types/Vault.ts
> +    } else {
Can also remove the else here

2021-08-04 04:43 UTC, xiangzhe0812 approved these changes

2021-08-04 04:44 UTC, rellfy approved these changes

2021-08-04 04:45 UTC, merged