181
handle-fi/handle-sdk pull request #193
Opened 2022-08-11 03:02 UTC by Preston-Harrison

resolves #181

2022-08-11 03:11 UTC, rellfy commented on src/abis/handle/handle-routers/RouterHpsmHlpCurveV2.json
> +{
Let's import this from the `handle-routes` package.
Just need to add a `.npmrc` file to the root folder with
```
registry=https://registry.npmjs.org
@handle-fi:registry=https://npm.pkg.github.com/
```
and then `yarn add @handle-fi/handle-routes`

2022-08-11 03:27 UTC, rellfy requested changes

2022-08-11 03:27 UTC, rellfy commented on src/components/Convert/routes/hlpToCurve.ts
> +    const tokenManager = new HandleTokenManager([]);
Don't we already have an instance somewhere? If not, we should. We can just import it then, instead of creating it on each quote

2022-08-11 03:27 UTC, rellfy commented on src/components/Convert/routes/hlpToCurve.ts
> +    .div(CURVE_FEE_DENOMINATOR - fees.toNumber());
Doesn't seem to be indented correctly? is the linter not working? :thinking:

2022-08-11 03:27 UTC, rellfy commented on src/components/Convert/routes/hlpToCurve.ts
> +    const [amountOut, fees] = await Promise.all([amountOutPromise, feesPromise]);
These could be placed in a new function, eg. `getAmountOutAndFees` to reduce the complexity of this one. It doesn't have to be added to an util, it can be a private function in this file

2022-08-11 03:27 UTC, rellfy commented on src/components/Convert/routes/hlpToCurve.ts
> +    const TokenManager = new HandleTokenManager();
Should also use the SDK singleton here

2022-08-11 03:27 UTC, rellfy commented on src/components/Convert/routes/psmToHlpToCurve.ts
> +  await tokenManager.initialLoad;
Could also use the singleton here (but keep the `await tokenManager.initialLoad`). This might be in every route so we can refactor those.

2022-08-11 03:27 UTC, rellfy commented on src/utils/convert-utils.ts
> +} | null;
We should try not to do this. The type should be 
```suggestion
export type HlpToCurvePath = {
  hlpToken: string;
  hlpCurveToken: string;
  curveToken: string;
  pool: string;
  factory: string;
};
```

2022-08-11 03:27 UTC, rellfy commented on src/utils/convert-utils.ts
> +  if (network !== "arbitrum") return null;
Instead of returning null, please throw an error here. Seems like the null check is being done on the caller, we want to prevent this.

2022-08-12 00:44 UTC, Preston-Harrison commented on src/utils/convert-utils.ts
> +  if (network !== "arbitrum") return null;
done

2022-08-12 00:44 UTC, Preston-Harrison commented on src/utils/convert-utils.ts
> +} | null;
done

2022-08-12 00:44 UTC, Preston-Harrison commented on src/components/Convert/routes/psmToHlpToCurve.ts
> +  await tokenManager.initialLoad;
done

2022-08-12 00:44 UTC, Preston-Harrison commented on src/components/Convert/routes/hlpToCurve.ts
> +    const TokenManager = new HandleTokenManager();
done

2022-08-12 00:44 UTC, Preston-Harrison commented on src/components/Convert/routes/hlpToCurve.ts
> +    const [amountOut, fees] = await Promise.all([amountOutPromise, feesPromise]);
done

2022-08-12 00:45 UTC, Preston-Harrison commented on src/components/Convert/routes/hlpToCurve.ts
> +    .div(CURVE_FEE_DENOMINATOR - fees.toNumber());
not sure about the linter, but I indented it.

2022-08-12 00:45 UTC, Preston-Harrison commented on src/components/Convert/routes/hlpToCurve.ts
> +    const tokenManager = new HandleTokenManager([]);
made a single instance, which is imported across the sdk

2022-08-12 00:45 UTC, Preston-Harrison commented on src/abis/handle/handle-routers/RouterHpsmHlpCurveV2.json
> +{
this does not work as handle-routes relies on external private packages

2022-08-12 01:00 UTC, nabsta-eth approved these changes

2022-08-12 04:14 UTC, rellfy approved these changes

2022-08-12 04:18 UTC, nabsta-eth approved these changes

2022-08-12 04:27 UTC, merged