copy routes abi
handle-fi/handle-sdk pull request #200
Opened 2022-08-17 00:27 UTC by Preston-Harrison

resolves #195

2022-08-17 23:21 UTC, rellfy reviewed
I think we should go with a slightly different approach.
The script could
- Run `npm install` on the packages we need eg. handle-routes
- Copy the files across
- Remove the npm lockfile

That way we just need to be authenticated to the private registry, we don't need a local environment setup in a way that the script needs to for it to work.

2022-08-17 23:29 UTC, nabsta-eth approved these changes

2022-08-17 23:31 UTC, rellfy commented
We should also gitignore the output folder for the scripts. The publish GH Action file should run the `copy-routes-abi` command before publishing

2022-08-17 23:31 UTC, rellfy requested changes
Good start, see the comments above

2022-08-18 02:37 UTC, rellfy submitted a review, later dismissed

2022-08-18 03:21 UTC, nabsta-eth submitted a review, later dismissed

2022-08-18 04:00 UTC, rellfy approved these changes

2022-08-18 04:05 UTC, nabsta-eth approved these changes

2022-08-18 04:05 UTC, merged