172 - add route from hLP to balancer
handle-fi/handle-sdk pull request #212
Opened 2022-08-25 06:56 UTC by Preston-Harrison

resolves #172

2022-08-26 00:19 UTC, Preston-Harrison commented
waiting on new handle routes version

2022-08-26 04:44 UTC, nabsta-eth approved these changes

2022-08-29 00:30 UTC, rellfy requested changes
Looks good generally, I think some things can be improved

2022-08-29 00:30 UTC, rellfy commented on src/components/Convert/routes/hlpToBalancer.ts
> +  console.log();
```suggestion
```

2022-08-29 00:30 UTC, rellfy commented on src/types/lpStaking.ts
> +export type LPStakingPlatformName = "handle" | "sushi" | "curve" | "balancer";
Could you please refactor the name of these to PascalCase?
```
LpStakingPoolName
LpStakingPoolNameMap
LpStakingPlatformName
```

2022-08-29 00:30 UTC, rellfy commented on src/types/lpStaking.ts
> +type LPStakingPoolDetailsBase = {
```
LpStakingPoolDetailsBase
```

2022-08-29 00:30 UTC, rellfy commented on src/types/lpStaking.ts
> +export type LPStakingPoolDetails =
```
LpStakingPoolDetails
```

2022-08-29 00:30 UTC, rellfy commented on src/types/lpStaking.ts
>  export type LPStakingPool = {
```
LpStakingPool
```

2022-08-29 00:30 UTC, rellfy commented on src/utils/convert-utils.ts
> +  mustExist(tokenOutResponse, `token out not in pool with id ${poolId}`);
```suggestion
  const tokenInResponse = mustExist(
    pool.tokens.find(
      (token: any) => token.address.toLowerCase() === tokenIn.toLowerCase()
    ),
    `token in not in pool with id ${poolId}`
  );
  const tokenOutResponse = mustExist(
    pool.tokens.find(
      (token: any) => token.address.toLowerCase() === tokenOut.toLowerCase()
    ),
    `token out not in pool with id ${poolId}`
  );
```
I think it would be better to either use the return value of `mustExist` or just do an `if (!tokeninResponse) throw new Error(...`.

2022-08-29 00:30 UTC, rellfy commented on src/utils/convert-utils.ts
> +type PoolPairBase = {
It looks like balancer pools are simply called "Pool". This can get very confusing because balancer is just one of the pools we have. Please move the balancer utils to its own module, e.g. `src/utils/balancer`, and also rename all balancer-related types and functions to explicitly mention Balancer.

2022-08-29 00:30 UTC, rellfy commented on src/utils/general-utils.ts
> +    throw new Error(`'${name}' is required, but missing`);
How about
```suggestion
    throw new Error(`mustExist: "${name}" does not exist`);
```

2022-08-29 00:30 UTC, rellfy commented on src/components/Convert/routes/hlpToBalancer.ts
> +  ];
`pairFromString` would be more concise here:
```suggestion
  const pairs: Pair[] = [
    pairFromString(`${path.tokenIn.symbol}/USD`),
    pairFromString(`${path.hlpBalancerToken.symbol}/USD`)
  ];

```

2022-08-29 00:30 UTC, rellfy commented on src/utils/convert-utils.ts
> +  const poolPairData = await getPoolPairData(network, poolId, tokenIn, tokenOut);
If we add the output of `getPoolPairData` as an argument here then we can unit test this function without any network requests.

2022-08-29 01:13 UTC, Preston-Harrison commented on src/components/Convert/routes/hlpToBalancer.ts
> +  ];
I don't see the benefit of casting the pair to a string only to call pairFromString

2022-08-29 01:13 UTC, Preston-Harrison commented on src/utils/convert-utils.ts
> +  const poolPairData = await getPoolPairData(network, poolId, tokenIn, tokenOut);
good point

2022-08-29 02:18 UTC, rellfy commented on src/components/Convert/routes/hlpToBalancer.ts
> +  ];
It's for readability, less code. We are not casting it to a string, it is already a string, we just concatenate it.

2022-08-29 02:24 UTC, rellfy commented on src/utils/convert-utils.ts
> +  if (!graphUrl) return [];
Isn't the url always expected to be present? We should probably throw here instead.

2022-08-29 02:24 UTC, rellfy commented on src/utils/convert-utils.ts
> +let curvePoolCache: CurvePoolDetailsWithToken[] | undefined;
Why allow undefined vs just keeping the array empty if nothing is cached?

2022-08-29 02:28 UTC, Preston-Harrison commented on src/utils/convert-utils.ts
> +let curvePoolCache: CurvePoolDetailsWithToken[] | undefined;
because there needs to be a way to determine whether or not the cache has originally been loaded

2022-08-29 02:29 UTC, Preston-Harrison commented on src/utils/convert-utils.ts
> +  if (!graphUrl) return [];
just removed the check for null. that should not have been there, a remnant of a reverted refactor

2022-08-29 02:46 UTC, rellfy approved these changes

2022-08-29 04:06 UTC, nabsta-eth approved these changes

2022-08-29 04:08 UTC, merged