Add parseNativeToWrapped
handle-fi/handle-sdk pull request #267
Opened 2022-10-19 06:20 UTC by Preston-Harrison

resolves #264

2022-10-19 06:59 UTC, Preston-Harrison commented
sonarcloud is mad because I am using a deprecated function in a test

2022-10-20 00:29 UTC, brettvniekerk commented on src/components/TokenManager/HandleTokenManager.ts
> +  public parseNativeToWrapped(token: TokenInfo): {
why not just return the wrapped token or `undefined`?

2022-10-20 00:29 UTC, brettvniekerk commented on src/components/TokenManager/HandleTokenManager.ts
> +  public parseNativeToWrapped(token: TokenInfo): {
if `undefined` then the calling function knows that the token isn't native

2022-10-20 00:30 UTC, brettvniekerk commented on src/components/TokenManager/HandleTokenManager.ts
> +    if (!wrappedNative) throw new Error("");
no error message?

2022-10-20 00:31 UTC, brettvniekerk commented on src/components/TokenManager/index.ts
> +  public getWrappedNativeToken(network: Network | number) {
this and `parseNativeToWrapped` seem to do the same thing

2022-10-20 00:32 UTC, brettvniekerk commented on src/config/TokenLists/misc-tokens.json
> +  "version": {
`1.0.0`?

2022-10-20 00:34 UTC, brettvniekerk requested changes
few things to address

2022-10-20 00:43 UTC, Preston-Harrison commented on src/config/TokenLists/misc-tokens.json
> +  "version": {
yes

2022-10-20 00:45 UTC, Preston-Harrison commented on src/components/TokenManager/index.ts
> +  public getWrappedNativeToken(network: Network | number) {
getWrappedNativeToken gets the wrapped native token. parseNativeToWrapped returns the wrapped native token only if the input token is native

2022-10-20 00:50 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +    if (!wrappedNative) throw new Error("");
lol

2022-10-20 00:52 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +  public parseNativeToWrapped(token: TokenInfo): {
The purpose of this function is to be similar to the utility function checkForHlpNativeToken, but not throw if the input token is not an hLP token. I'll admit the output is a bit strange, but it serves a common purpose really well. See below.

```javascript
const { isInputNative, parsedToken } = tokenManager.parseNativeToWrapped(possiblyNativeToken);
if (isInputNative) {
    contract.doSomethingEth(parsedToken.address, { value: someValue });
} else {
    contract.doSomething(parsedToken.address, someValue);
}
```

I don't think it should return undefined, as that is not common for handling an invalid input into a parsing function. if anything it should throw if the input is not a native token. But then it gets really annoying as you have to wrap the thing in a try-catch.

2022-10-20 01:38 UTC, brettvniekerk commented on src/components/TokenManager/HandleTokenManager.ts
> +  public parseNativeToWrapped(token: TokenInfo): {
i dont like how both properties essentially reflect the same thing - it seems like an unnecessary doubling-up of data. i would rather you use a utility function or refactor to use one return type - but if it is common for parsing functions then dont feel the need

2022-10-20 01:39 UTC, brettvniekerk commented on src/components/TokenManager/index.ts
> +  public getWrappedNativeToken(network: Network | number) {
ah, nevermind then

2022-10-20 01:41 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +  public parseNativeToWrapped(token: TokenInfo): {
They don't reflect the same thing when the token passed in is WETH

2022-10-20 02:32 UTC, rellfy commented on src/components/TokenManager/HandleTokenManager.ts
> +    const tokens = this.getHlpTokens(network);
All these hLP token getter functions that were `getLoadedTokens` and filtering by `isHlpToken` themselves. Now that they are getting tokens by `getHlpTokens`, they should no longer filter by `isHlpToken` as they're still doing

2022-10-20 02:34 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +    const tokens = this.getHlpTokens(network);
good point

2022-10-20 02:40 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +    const tokens = this.getHlpTokens(network);
fixed

2022-10-20 02:40 UTC, Preston-Harrison commented
sonarcloud errors can be ignored

2022-10-20 02:55 UTC, rellfy approved these changes
Do you need to increase the package version before merging?

2022-10-20 03:37 UTC, Preston-Harrison commented
> Do you need to increase the package version before merging?

no, we can release it next time

2022-10-20 03:38 UTC, brettvniekerk commented on src/components/TokenManager/HandleTokenManager.ts
> +    const tokens = this.getFromCache(HANDLE_TOKEN_KEY)?.tokens.filter((t) =>
no single letter vars, please call `token`

2022-10-20 03:38 UTC, brettvniekerk approved these changes
just one thing to look at, otherwise LGTM

2022-10-20 03:43 UTC, Preston-Harrison commented on src/components/TokenManager/HandleTokenManager.ts
> +    const tokens = this.getFromCache(HANDLE_TOKEN_KEY)?.tokens.filter((t) =>
not a big deal here, meaning is obvious IMO

2022-10-20 03:43 UTC, Preston-Harrison commented
force merging as coverage is failing due to oracles

2022-10-20 03:44 UTC, merged