Resolves 83
handle-fi/handle-sdk pull request #87
Opened 2022-05-03 04:50 UTC by Preston-Harrison

2022-05-03 06:27 UTC, nabsta-eth approved these changes

2022-05-03 06:44 UTC, bitcoinbrisbane commented on src/components/Trade/getLiquidationPrice.ts
> +    }
Could we do this with a ternary?

2022-05-03 06:48 UTC, bitcoinbrisbane commented on src/components/Trade/index.ts
> +  getNextAveragePrice
Seems we broke alphabetical order.

2022-05-03 06:49 UTC, bitcoinbrisbane commented on src/components/Trade/splitPositionArray.ts
> +  return positionArray;
Can this be done with a .map ?

2022-05-03 06:55 UTC, Preston-Harrison commented on src/components/Trade/splitPositionArray.ts
> +  return positionArray;
not really, since the returned array has a different size of the initial array. Stack overflow says this is alright https://stackoverflow.com/a/7273717/17862051

2022-05-03 06:58 UTC, Preston-Harrison commented on src/components/Trade/getLiquidationPrice.ts
> +    }
It could be, but this function was taken from GMX's frontend and where possible I think the structure that was copied over should be preserved

2022-05-03 07:01 UTC, Preston-Harrison commented on src/components/Trade/index.ts
> +  getNextAveragePrice
fixed

2022-05-03 07:09 UTC, bitcoinbrisbane commented on src/components/Trade/getNextAveragePrice.ts
> +  }
Seems like this could be more concise

2022-05-03 07:09 UTC, bitcoinbrisbane requested changes
Few minor things

2022-05-03 07:10 UTC, bitcoinbrisbane commented on src/components/Trade/splitPositionArray.ts
> +  return positionArray;
Ok

2022-05-03 07:11 UTC, Preston-Harrison commented on src/components/Trade/getNextAveragePrice.ts
> +  }
same here as with the ternary issue, I'd prefer to leave it untouched from the gmx frontend. Do you think it is worth changing it regardless?

2022-05-03 07:15 UTC, nabsta-eth approved these changes

2022-05-03 09:21 UTC, rellfy commented on src/components/Trade/getNextAveragePrice.ts
> +  }
If it's really the same line on both if/else, then yes just make it a single line

2022-05-03 23:34 UTC, Preston-Harrison commented on src/components/Trade/getNextAveragePrice.ts
> +  }
it isn't, the add and sub are switched around

2022-05-04 00:49 UTC, rellfy approved these changes

2022-05-04 00:55 UTC, xcjlo985 commented on package.json
> +  "version": "0.0.59",
Usually you increment the version when you cut a release, not couple it directly to a feature branch

2022-05-04 00:57 UTC, rellfy commented on package.json
> +  "version": "0.0.59",
What if we'll release after merging?

2022-05-04 01:15 UTC, Preston-Harrison commented on package.json
> +  "version": "0.0.59",
We are doing 1 PR 1 release, so I figure changing the version is the right move

2022-05-04 01:27 UTC, merged