91
handle-fi/handle-sdk pull request #92
Opened 2022-05-09 02:04 UTC by Preston-Harrison

resolves #91

2022-05-09 02:52 UTC, nabsta-eth submitted a review, later dismissed

2022-05-09 03:24 UTC, bitcoinbrisbane submitted a review, later dismissed
Few small things to look at

2022-05-09 03:24 UTC, bitcoinbrisbane commented on hardhat.config.ts
> +        url: "https://arb-mainnet.g.alchemy.com/v2/HORad5Nv96-kPzIx9oEPU0tCEiIVp-Oz",
Should this not be in process.env?

2022-05-09 03:24 UTC, bitcoinbrisbane commented on src/components/Convert/getPegStabilityQuote.ts
> +    throw new Error("No HPSM for network '" + network + "'");
Probably better to do template / backtickets
```suggestion
    throw new Error(`No HPSM for network ${network}`);
```

2022-05-09 03:24 UTC, bitcoinbrisbane commented on src/components/Convert/getPegStabilityTransaction.ts
> +  return tx;
This could be cleaner.
```suggestion
  if (isDeposit) {
    return(await hpsm.populateTransaction.deposit(toToken, fromToken, fromAmount));
  } 
  if (isWithdraw) {
    return(await hpsm.populateTransaction.withdraw(fromToken, toToken, fromAmount));
  } 
  throw new Error(`There is no peg between ${fromToken} and ${toToken}`);
```

2022-05-09 03:24 UTC, bitcoinbrisbane commented on src/config/hlp.ts
> +
Why are these guys strings?

2022-05-09 03:42 UTC, rellfy commented on hardhat.config.ts
> +        url: "https://arb-mainnet.g.alchemy.com/v2/HORad5Nv96-kPzIx9oEPU0tCEiIVp-Oz",
Not needed in this case because it's a public client key

2022-05-09 03:44 UTC, rellfy requested changes
Please make a new branch off 91, and do the refactoring that we discussed with the convert Routes. Then we can merge that into this one, and then this one into master.

2022-05-09 04:06 UTC, Preston-Harrison commented on src/config/hlp.ts
> +
I used strings for bignumber calculations, but you are right, that is not needed here

2022-05-09 04:07 UTC, Preston-Harrison commented on src/config/hlp.ts
> +
Alot of gas calculations accept strings as an input. Notably the Quote object type

2022-05-09 04:23 UTC, rellfy commented on src/config/hlp.ts
> +
those should be refactored to, most likely, the [BigNumberish](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumberish) type

2022-05-10 23:52 UTC, nabsta-eth approved these changes

2022-05-11 03:07 UTC, Preston-Harrison commented on src/config/hlp.ts
> +
done

2022-05-11 03:10 UTC, rellfy requested changes

2022-05-11 03:10 UTC, rellfy commented on src/components/Convert/isTokenPegged.ts
> +import { providers, Signer } from "ethers";
Can you move this file into `routes/psm`?

2022-05-11 03:11 UTC, Preston-Harrison commented on src/components/Convert/isTokenPegged.ts
> +import { providers, Signer } from "ethers";
only because you asked nicely :)

2022-05-11 03:16 UTC, rellfy approved these changes

2022-05-11 03:17 UTC, rellfy commented
Resolves #93

2022-05-11 07:07 UTC, nabsta-eth approved these changes

2022-05-12 23:34 UTC, closed without merging