93
handle-fi/handle-sdk pull request #94
Opened 2022-05-10 03:04 UTC by Preston-Harrison

resolves #93

2022-05-10 07:32 UTC, rellfy commented on src/components/Convert/baseApiUrls.ts
> +};
These should be moved to their routes

2022-05-10 23:35 UTC, Preston-Harrison commented on src/components/Convert/baseApiUrls.ts
> +};
done

2022-05-10 23:50 UTC, nabsta-eth approved these changes

2022-05-11 00:30 UTC, rellfy requested changes
Looking good, I have a few more suggestions

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/oneInch.ts
> +  };
Please move this to `types/network.ts` and import from there. Also, isn't it better to just name it `networkNameToId`? `Map` seems a bit redundant.

If we had instead named `ethereum` as `mainnet` or `homestead`, and `polygon` as `matic`, we could have used `ethers.providers.getNetwork(network).chainId;` here.

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/psm.ts
> +let transactionFeeCache: Record<Network, BigNumber | null> = {
```suggestion
const transactionFeeCache: Record<Network, BigNumber | null> = {
```
This one can be const. It only has to be `let` if you re-assign the variable itself.

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/psm.ts
> +    throw new Error("No HPSM for network '" + network + "'");
```suggestion
    throw new Error(`No HPSM for network "${network}"`);
```

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/psm.ts
> +  const isDeposit = await isTokenPegged(toToken.address, fromToken.address, provider, network);
```suggestion
  const [isWithdraw, isDeposit] = await Promise.all([
    isTokenPegged(fromToken.address, toToken.address, provider, network),
    isTokenPegged(toToken.address, fromToken.address, provider, network)
  ]);
```
Please make sure to do that whenever you have a sequence of `await` where the lines don't depend on each other

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/weights.ts
> +export const HLP_TOKEN_WEIGHT = 100;
Please rename to `HLP_ADD_REMOVE_WEIGHT`.

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/routes/weights.ts
> +export const LIQUIDITY_WEIGHT = 110;
Please rename to `HLP_SWAP_WEIGHT`

2022-05-11 00:30 UTC, rellfy commented on src/components/Convert/Convert.ts
> +      )
The lines up to 
```
if (route.calculatedWeight === 0) {
      throw new Error(`No route found for ${input.fromToken.symbol} and ${input.toToken.symbol}`);
    }
```
Are mostly duplicate with `getQuote`. You can make a new function to get all lines up to `const route = weightedRoutes[0];` eg `const router = getRoute(input)`, and then change this
```
.then((calculatedWeight) => ({
            handler: route.quote,
            calculatedWeight: calculatedWeight
          }))
```
to this
```
.then((calculatedWeight) => ({
            route,
            calculatedWeight
          }))
```
so that you can do `router.route.transaction()` on `getSwap` and `router.route.quote()` on `getQuote`.

2022-05-11 00:37 UTC, Preston-Harrison commented on src/components/Convert/routes/oneInch.ts
> +  };
yeah will do. just copied this over from previous convert class

2022-05-11 00:38 UTC, Preston-Harrison commented on src/components/Convert/routes/oneInch.ts
> +  };
I dont think this should go in types as it isn't a type. It should be in the config

2022-05-11 01:32 UTC, Preston-Harrison commented on src/components/Convert/routes/psm.ts
> +let transactionFeeCache: Record<Network, BigNumber | null> = {
done

2022-05-11 01:32 UTC, Preston-Harrison commented on src/components/Convert/routes/psm.ts
> +    throw new Error("No HPSM for network '" + network + "'");
done

2022-05-11 01:32 UTC, Preston-Harrison commented on src/components/Convert/routes/psm.ts
> +  const isDeposit = await isTokenPegged(toToken.address, fromToken.address, provider, network);
done

2022-05-11 01:32 UTC, Preston-Harrison commented on src/components/Convert/routes/weights.ts
> +export const LIQUIDITY_WEIGHT = 110;
done

2022-05-11 01:33 UTC, Preston-Harrison commented on src/components/Convert/Convert.ts
> +      )
moved sorting the routes to its own function

2022-05-11 01:45 UTC, Preston-Harrison commented on src/components/Convert/routes/oneInch.ts
> +  };
used the one in the constants file, didnt know it was there

2022-05-11 02:04 UTC, Preston-Harrison commented on src/components/Convert/routes/oneInch.ts
> +export const get1InchBaseUrl = (network: Network) => {
done

2022-05-11 02:04 UTC, Preston-Harrison commented on src/components/Convert/routes/zeroX.ts
> +export const get0xBaseUrl = (network: Network) =>
done

2022-05-11 03:05 UTC, rellfy approved these changes

2022-05-11 03:07 UTC, merged